name: CI

on:
  push:
    branches: [ master ]
    paths:
      - packages/**
  pull_request:
    paths:
      - packages/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    name: "Build&Test: node-${{ matrix.node-version }}, ${{ matrix.os }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install deps
      run:  yarn --frozen-lockfile
    
    - name: Build galaco
      run: |
        cd packages/galaco
        yarn run build
